spring:
  application:
    name: organization-service
  config:
    import:
      optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
  cloud:
    stream:
     bindings:
       output:
         destination: orgChangeTopic
         content-type: application/json
     kafka:
       binder:
          brokers:
            - kafkaserver:9092



logging:
  level:
    com.cts: debug
keycloak:
  realm: ostock-realm
  auth-server-url: http://keycloak:8090/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: zGfLk4M7BIpyFHx87RPlvASazL7TfPaU
  use-resource-role-mappings: true
  bearer-only: true
