spring:
  application:
    name: organization-service
  config:
    import:
      optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
logging:
  level:
    com.cts: debug
keycloak:
  realm: ostock-realm
  auth-server-url: http://keycloak:8090/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: pVFMAhgJiocQdUpHYhBlb0KQ5JMWcDrB
  use-resource-role-mappings: true
  bearer-only: true
