spring:
  application:
    name: organization-service
  config:
    import:
      optional:configserver:http://localhost:8888
    activate:
      on-profile: dev
  cloud:
    stream:
     bindings:
       output:
         destination: orgChangeTopic
         content-type: application/json
     kafka:
       binder:
          brokers:
            - kafkaserver:9092



logging:
  level:
    com.cts: debug
